### ISSUE TITLE
PantherScore 1.03 no longer exists

### ISSUE THREAD

**Issue by andrewyatz** [Ensembl/homebrew-ensembl#7]
The compara cask currently fails to install because pantherscore fails to install

The zip file ftp://ftp.pantherdb.org/hmm_scoring/10.0/1.03/pantherScore1.03.zip no longer exists on panther's FTP site. There is another binary for pantherscore 2.0 from ftp://ftp.pantherdb.org/hmm_scoring/11.1/pantherScore2.0/ but this is a directory not a single zip file. 

There is also a version 2.1 available from ftp://ftp.pantherdb.org/hmm_scoring/12.0/pantherScore2.1/. 

I don't know which one of these we want but if panther scores can be retired then we need to figure out what's changed in these versions and switch accordingly if still used. Also will have an impact on https://raw.githubusercontent.com/Ensembl/pantherScore/master/pantherScore1.03.patch

Assigning to @muffato to answer the bigger questions about which is the right panther score to use. Feel free to re-assign once we have answers :)

**Comment by muffato** [comment]
No it's really the version 1.03 that we need. I'll check further on their website and ftp in case they've got a copy somewhere else. Otherwise I'll just package the (patched) version we have at the moment and put it on our repo

**Comment by andrewyatz** [comment]
Done and pushed out to https://github.com/Ensembl/pantherScore
